# Generated by Django 4.2 on 2023-06-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='inbound_date',
            new_name='date',
        ),
    ]
